namespace HerhangiOT.GameServer.Enums
{
    public enum ConditionParameters
    {
        Owner = 1,
        Ticks = 2,
        //Outfit = 3,
        HealthGain = 4,
        HealthTicks = 5,
        ManaGain = 6,
        ManaTicks = 7,
        Delayed = 8,
        Speed = 9,
        LightLevel = 10,
        LightColor = 11,
        SoulGain = 12,
        SoulTicks = 13,
        MinValue = 14,
        MaxValue = 15,
        StartValue = 16,
        TickInterval = 17,
        ForceUpdate = 18,
        SkillMelee = 19,
        SkillFist = 20,
        SkillClub = 21,
        SkillSword = 22,
        SkillAxe = 23,
        SkillDistance = 24,
        SkillShield = 25,
        SkillFishing = 26,
        StatMaxHitPoints = 27,
        StatMaxManaPoints = 28,
        //StatSoulPoints = 29,
        StatMagicPoints = 30,
        StatMaxHitPointsPercent = 31,
        StatMaxManaPointsPercent = 32,
        //StatSoulPointsPercent = 33,
        StatMagicPointsPercent = 34,
        PeriodicDamage = 35,
        SkillMeleePercent = 36,
        SkillFistPercent = 37,
        SkillClubPercent = 38,
        SkillSwordPercent = 39,
        SkillAxePercent = 40,
        SkillDistancePercent = 41,
        SkillShieldPercent = 42,
        SkillFishingPercent = 43,
        BuffSpell = 44,
        SubID = 45,
        Field = 46,
    }
}