namespace HerhangiOT.GameServer.Enums
{
    public enum MagicEffects : byte
    {
	    None,

	    DrawBlood = 1,
	    LoseEnergy = 2,
	    Poff = 3,
	    BlockHit = 4,
	    ExplosionArea = 5,
	    ExplosionHit = 6,
	    FireArea = 7,
	    YellowRings = 8,
	    GreenRings = 9,
	    HitArea = 10,
	    Teleport = 11,
	    EnergyHit = 12,
	    MagicBlue = 13,
	    MagicRed = 14,
	    MagicGreen = 15,
	    HitByFire = 16,
	    HitByPoison = 17,
	    MortArea = 18,
	    SoundGreen = 19,
	    SoundRed = 20,
	    PoisonArea = 21,
	    SoundYellow = 22,
	    SoundPurple = 23,
	    SoundBlue = 24,
	    SoundWhite = 25,
	    Bubbles = 26,
	    Craps = 27,
	    GiftWraps = 28,
	    FireworkYellow = 29,
	    FireworkRed = 30,
	    FireworkBlue = 31,
	    Stun = 32,
	    Sleep = 33,
	    WaterCreature = 34,
	    GroundShaker = 35,
	    Hearts = 36,
	    FireAttack = 37,
	    EnergyArea = 38,
	    SmallClouds = 39,
	    HolyDamage = 40,
	    BigClouds = 41,
	    IceArea = 42,
	    IceTornado = 43,
	    IceAttack = 44,
	    Stones = 45,
	    SmallPlants = 46,
	    Carniphila = 47,
	    PurpleEnergy = 48,
	    YellowEnergy = 49,
	    HolyArea = 50,
	    BigPlants = 51,
	    Cake = 52,
	    GiantIce = 53,
	    WaterSplash = 54,
	    PlantAttack = 55,
	    TutorialArrow = 56,
	    TutorialSquare = 57,
	    MirrorHorizontal = 58,
	    MirrorVertical = 59,
	    SkullHorizontal = 60,
	    SkullVertical = 61,
	    Assassin = 62,
	    StepsHorizontal = 63,
	    BloodySteps = 64,
	    StepsVertical = 65,
	    YalahariGhost = 66,
	    Bats = 67,
	    Smoke = 68,
	    Insects = 69,
	    Dragonhead = 70,
	    OrcShaman = 71,
	    OrcShamanFire = 72,
	    Thunder = 73,
	    Ferumbras = 74,
	    ConfettiHorizontal = 75,
	    ConfettiVertical = 76,
	    // 77-157 are empty
	    BlackSmoke = 158,
	    // 159-166 are empty
	    RedSmoke = 167,
	    YellowSmoke = 168,
	    GreenSmoke = 169,
	    PurpleSmoke = 170,
    }
}
